# Generated by Django 3.0.2 on 2020-03-18 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('empresa', models.CharField(default='Nombre de la empresa', max_length=20)),
                ('identifier', models.CharField(default='autogenerateduniqueid-custom', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default='00.00', max_digits=10)),
                ('payment', models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de debito'), ('TD', 'Tarjeta de credito')], default='EF', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
