# Generated by Django 3.0.4 on 2020-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0003_auto_20200331_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='companyIdentifier',
            field=models.CharField(default='000-000-000', max_length=11),
        ),
    ]
