# Generated by Django 3.0.4 on 2020-04-17 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0005_auto_20200408_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default=datetime.date.today, max_length=30),
        ),
    ]
