# Generated by Django 3.0.4 on 2020-04-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0009_auto_20200417_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='17/04/2020', max_length=45),
        ),
    ]
