# Generated by Django 3.0.4 on 2020-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibo', '0010_auto_20200417_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='11/05/2020', max_length=35),
        ),
    ]
