# Generated by Django 3.0.2 on 2020-03-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
