# Generated by Django 3.0.2 on 2020-03-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
