# Generated by Django 3.0.2 on 2020-03-12 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
