# Generated by Django 3.0.2 on 2020-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200312_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='empresa',
            field=models.CharField(default='default_value', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='identifier',
            field=models.CharField(default='default_value', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de debito'), ('TD', 'Tarjeta de credito')], default='EF', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default='999', max_digits=10),
        ),
    ]
